{% set name = "git-sizer" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/github/git-sizer/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 07a5ac5f30401a17d164a6be8d52d3d474ee9c3fb7f60fd83a617af9f7e902bb

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('go') }}

test:
  requires:
    - git
  commands:
    - git init .
    - git-sizer -v

about:
  home: https://github.com/github/git-sizer
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Compute various size metrics for a Git repository, flagging those that might
    cause problems

extra:
  recipe-maintainers:
    - dbast
