{% set name = "git-sizer" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/github/git-sizer/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 5dafc4014d6bfae40e678d72c0a67a29cd9ac7b38a0894fc75ab8c05a9064a4b

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('go') }}

test:
  requires:
    - git
  commands:
    - git init .
    - git-sizer -v

about:
  home: https://github.com/github/git-sizer
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Compute various size metrics for a Git repository, flagging those that might
    cause problems

extra:
  recipe-maintainers:
    - dbast
