travis:
  secure:
    BINSTAR_TOKEN: CGf9fYpwvPcTsIWvYAFv1sOL0HD8eDzs8MhCrxiz0vKpkSMHqEfs8FivQuDfGuHS5Mo9pLoMgBpW+lIMfGUmkhZ63a9j39W2VxJ5RjBvArY18MX4VLDESCqADQAwsB1QInRywWVZ5mpt+8BKeq22xQXUI2q9j9biioAYg7e7CjwnebIjjS/hMezoi9c93WdG/TiCur9jKtb8ViaSkf+V3AdHxFhmX5XuLOM4F/DfMFO4qF/l/Pm3UJj56EBalx19IHiPxUBfl9QxmStEzFlWEexEQ1RsKLTEdqi2Bta/+ImLoSCTK8qvLo1fvsh/kCCkgTu8ibvO8nu7jmr3TaR7fBlJCplbcWhBHoECGBP0fhUhy/DyNOxLH5a8akxQ3aBhcTrsegfu6Ob+m9r4u0W1G7w54t9UgYPTilnG/S/Z5wdWaJKTK/cEi6sLuI6RrnTHCoVo6vs8kS7wdq9uoGCU0umoH13zu21j1+Xk27jDUXj03aRmOH55keOF6kVz+nAINg3XL8POywIEPlkoIXbv2XqtI2cdidLd/MQhlPi/4aOVfT9TVB1Gz8+qOfjT2hTcVuZ3uo7e2PVsvKrRriK7D4si9bruLw54gxbkLp4P9NizBvVVt8hanTx6nt1fTgWU6t7i+zYgcStbSR9vz1CN5dAsUB5MOvnX+Jjnd1ECEWU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
conda_forge_output_validation: true
